### ISSUE TITLE
Setup Java development environment and create guide

### ISSUE THREAD

**Issue by timoteoponce** [timoteoponce/sandbox_film-store#1]
Setup your Java development environment and write a wiki page for it within this repository.

What tools do we need?
- OS: Windows, Linux or MacOs
- Container: [Docker](https://docs.docker.com/desktop/windows/install/)
- IDE: [Visual Studio code](https://code.visualstudio.com/)

What it's expected after your setup?
- That you can run the project from the IDE
- That you can change the code and compile it

Note: Do not install a local JDK, we will use [dev-containers](https://code.visualstudio.com/docs/remote/create-dev-container) for everything

**Comment by dabeyva** [comment]
Done 👍 
![image](https://user-images.githubusercontent.com/108372057/177229794-061081c3-a9cc-4049-aff8-130b0d8447ff.png)
