### ISSUE TITLE
Configure the development environment with Java-17

### ISSUE THREAD

**Issue by timoteoponce** [timoteoponce/sandbox_film-store#2]
We need to support the latest Java-17 LTS release, configure the maven project to run at least with this version.

Also verify that we are using UTF-8 in the compiler.

Where to check or update this? 
- In the Maven configuration

**Comment by dabeyva** [comment]
done 
<properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
  </properties>

**Comment by dabeyva** [comment]
![image](https://user-images.githubusercontent.com/108372057/179423320-3f8f5e10-e468-4a16-a508-d003831a82d7.png)
