### ISSUE TITLE
Update the current console application to be a web application

### ISSUE THREAD

**Issue by timoteoponce** [timoteoponce/sandbox_film-store#3]
The application as it is it's a standard console application, the goal of our film_store is to be a web application, please update the project to comply to this requirement.

What to do?

1. Add the [Javalin libraries](https://javalin.io)
2. Update the project trigger a web application Hello world page, see the [Javalin guide for this](https://javalin.io/documentation)
3. Structure the application to follow an MVC structure: Models with plain java objects at the moment, controllers with the routes and handling of flow, views with VueJs using the Javalin Support

**Comment by dabeyva** [comment]
1. Add the Javalin libraries
 ```
<dependency>
      <groupId>io.javalin</groupId>
      <artifactId>javalin</artifactId>
      <version>4.6.4</version>
  </dependency>
```
2. Update the project trigger a web application Hello world page, see the Javalin guide for this
Public class App {
    
        public static void main(String[] args) {
             Javalin app = Javalin.create().start(7070);
            app.get("/", ctx -> ctx.result("Hello World"));
        }
    
}
3. Structure the application to follow an MVC structure: Models with plain java objects at the moment, controllers with the routes and handling of flow, views with VueJs using the Javalin Support
I can't fully understand, Help me !! please

**Comment by timoteoponce** [comment]
@dabeyva check the Vue support (JavalinVue) section in the documentation https://javalin.io/documentation#faq

Note: I don't see your code here, please create a pull request to merge your changes into this repository, a guide can be found at https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
